# vim: nospell

language: cpp
#git:
#  quiet: true
#  submodules: false
#branches:
#  only:
#    - /.*/

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

install:
  - cd ${HOME}
  - cmake_version=3.12.0
  - wget https://github.com/Kitware/CMake/releases/download/v${cmake_version}/cmake-${cmake_version}-Linux-x86_64.sh
  - chmod 764 ./cmake-${cmake_version}-Linux-x86_64.sh
  - ./cmake-${cmake_version}-Linux-x86_64.sh --include-subdir --skip-license
  - alias CMAKE=$(pwd)/cmake-${cmake_version}-Linux-x86_64/bin/cmake
  - alias CTEST=$(pwd)/cmake-${cmake_version}-Linux-x86_64/bin/ctest
  - alias CPACK=$(pwd)/cmake-${cmake_version}-Linux-x86_64/bin/cpack
#  - pip install --quiet --requirement ci-requirements.txt --requirement requirements.txt

script:
  - shopt -s expand_aliases
  - source_directory="${TRAVIS_BUILD_DIR}"
  - build_directory="${TRAVIS_BUILD_DIR}/../build"
  - mkdir "${build_directory}"
  - cd "${build_directory}"
  - CMAKE -D CMAKE_BUILD_TYPE=Release -D quality_checks:BOOL=off "${source_directory}"
#  - eval "${MATRIX_EVAL}"
#  - ${CXX} --version
